# Generated by Django 2.0 on 2020-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%Y%m%d/', verbose_name='图片'),
        ),
    ]
